name = "CBT New Horizons"
author = "Nrmot"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b3bde06a59cf08dc2c8670bd7f63c813f6c98a98e5f18ddbc30abb08f03fc17"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
