name = "CBT New Horizons"
author = "Nrmot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac63a1521f4ef70ce1cc1633dc2698891da2978f76ad81d4618cd3e3d3a0a70a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
