name = "CBT New Horizons"
author = "Nrmot"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4a050b4c8e4da1fba406a6fa0a9e6bf0a50eb93f286e1c11a09af3dc63d5272"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
