#loader multiblocked

// ELEMENTAL CONVERSION - PERIODIC TABLE CONVERSION RECIPES

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Susanium_to_11003")
    .duration(600)
    .inputItems([<ore:ingotSusanium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11003>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Dylantrum_to_11004")
    .duration(600)
    .inputItems([<ore:ingotDylantrum>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11004>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Agrastium_to_11005")
    .duration(600)
    .inputItems([<ore:ingotAgrastium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11005>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Ruslyium_to_11006")
    .duration(600)
    .inputItems([<ore:ingotRuslyium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:130>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Trinium_to_11007")
    .duration(600)
    .inputItems([<ore:ingotTrinium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11007>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Schrabidium_to_11009")
    .duration(600)
    .inputItems([<ore:ingotSchrabidium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11008>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Veridium_to_11010")
    .duration(600)
    .inputItems([<ore:ingotVeridium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11010>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Lunarium_to_11011")
    .duration(600)
    .inputItems([<ore:ingotLunarium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11011>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Etherium_to_11012")
    .duration(600)
    .inputItems([<ore:ingotEtherium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11012>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Xenynium_to_11013")
    .duration(600)
    .inputItems([<ore:ingotXenynium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11013>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Neptupitrium_to_11014")
    .duration(600)
    .inputItems([<ore:ingotNeptupitrium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11014>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Solimonium_to_11015")
    .duration(600)
    .inputItems([<ore:ingotSolimonium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11015>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Aetherium_to_11016")
    .duration(600)
    .inputItems([<ore:ingotAetherium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11016>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Quasarium_to_11017")
    .duration(600)
    .inputItems([<ore:ingotQuasarium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11017>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Laranium_to_11018")
    .duration(600)
    .inputItems([<ore:ingotLaranium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11018>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Pyranium_to_11019")
    .duration(600)
    .inputItems([<ore:ingotPyranium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11019>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Silisimmunium_to_11020")
    .duration(600)
    .inputItems([<ore:ingotSilisimmunium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11020>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Ryneurassium_to_11021")
    .duration(600)
    .inputItems([<ore:ingotRyneurassium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11021>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Supractinium_to_11022")
    .duration(600)
    .inputItems([<ore:ingotSupractinium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11022>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Puthanium_to_11023")
    .duration(600)
    .inputItems([<ore:ingotPuthanium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11023>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Coslynium_to_11024")
    .duration(600)
    .inputItems([<ore:ingotCoslynium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11024>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Yrattasium_to_11025")
    .duration(600)
    .inputItems([<ore:ingotYrattasium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11025>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Runevaline_to_11026")
    .duration(600)
    .inputItems([<ore:ingotRunevaline>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11026>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Neoveline-392_to_11027")
    .duration(600)
    .inputItems([<ore:ingotNeoveline-392>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11027>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Neoveline_to_11028")
    .duration(600)
    .inputItems([<ore:ingotNeoveline>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11028>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Cesarium_to_11029")
    .duration(600)
    .inputItems([<ore:ingotCesarium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11029>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Quannasarium_to_11030")
    .duration(600)
    .inputItems([<ore:ingotQuannasarium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11030>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Jadynomium_to_11031")
    .duration(600)
    .inputItems([<ore:ingotJadynomium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11031>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Jaumium_to_11032")
    .duration(600)
    .inputItems([<ore:ingotJaumium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11032>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Euronium_to_11033")
    .duration(600)
    .inputItems([<ore:ingotEuronium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11033>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Dimosonium_to_11034")
    .duration(600)
    .inputItems([<ore:ingotDimosonium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11034>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Krassium_to_11035")
    .duration(600)
    .inputItems([<ore:ingotKrassium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11035>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Dithermonium_to_11036")
    .duration(600)
    .inputItems([<ore:ingotDithermonium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11036>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Prassoppurium_to_11037")
    .duration(600)
    .inputItems([<ore:ingotPrassoppurium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11037>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Sunatrium_to_11038")
    .duration(600)
    .inputItems([<ore:ingotSunatrium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11038>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Bralyium_to_11039")
    .duration(600)
    .inputItems([<ore:ingotBralyium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11039>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Quintessium_to_11040")
    .duration(600)
    .inputItems([<ore:ingotQuintessium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11040>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Zephyrion_to_11041")
    .duration(600)
    .inputItems([<ore:ingotZephyrion>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11041>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Chronotite_to_11042")
    .duration(600)
    .inputItems([<ore:ingotChronotite>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11042>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Luminarite_to_11043")
    .duration(600)
    .inputItems([<ore:ingotLuminarite>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11043>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Pyrocore_to_11044")
    .duration(600)
    .inputItems([<ore:ingotPyrocore>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11044>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Spectresium_to_11045")
    .duration(600)
    .inputItems([<ore:ingotSpectresium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11045>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Aquamimite_to_11046")
    .duration(600)
    .inputItems([<ore:ingotAquamimite>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11046>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Terravium_to_11047")
    .duration(600)
    .inputItems([<ore:ingotTerravium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11047>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Psilunarite_to_11048")
    .duration(600)
    .inputItems([<ore:ingotPsilunarite>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11048>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Nebulium_to_11049")
    .duration(600)
    .inputItems([<ore:ingotNebulium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11049>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Scytronium_to_11050")
    .duration(600)
    .inputItems([<ore:ingotScytronium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11050>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Modulatum_to_11051")
    .duration(600)
    .inputItems([<ore:ingotModulatum>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11051>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Etharosium_to_11052")
    .duration(600)
    .inputItems([<ore:ingotEtharosium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11052>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();

// Recipe Autogenerated by Nrmot's Versatile Python Scripts
<mbd:recipe_map:ELEMENTAL_CONVERSION>.start()
    .name("Echotium_to_11054")
    .duration(600)
    .inputItems([<ore:ingotEchotium>*1, <hbm:particle_digamma>*1, <hbm:particle_higgs>*1, <hbm:particle_strange>*1, <hbm:particle_dark>*1])
    .outputItems(<gregtech:meta_ingot:11053>)
    .perTick(true)
    .inputEU(524288)
    .buildAndRegister();